#!/usr/bin/env bash

function habitat_brandonocasey_habitat_manage_vim_run() {
  local current_plugin_dir="$1"; shift
  local dotfiles_dir="$1"; shift
  # install vundle in the background if not installed

  local bundle_dir="$HOME/.vim/bundle/"
  local vundle_dir="$bundle_dir/Vundle.vim"
  local vundle_url="https://github.com/gmarik/Vundle.vim"
  if [ ! -f "$vundle_dir/README.md" ]; then
    mkdir -p "$vundle_dir"
    (cd "$bundle_dir" && git clone "$vundle_url" 2>/dev/null 1>/dev/null &)
  fi

  echo "\" be iMproved, required
set nocompatible

\" required
filetype off

function! SourceFiles(path, search)
  let path = expand(a:path)
  let files_found = system('find ' . path . ' -not -type l -name  ' . a:search)
  if empty(files_found)
    return
  endif
  for FILE in split(files_found, '\\n')
    exe 'source' FILE
  endfor
endfunction

\" Source in all vimc files
call SourceFiles('$dotfiles_dir', '*.vimc')

\" Use Vundle and source .vimp files
let vundle_readme=expand('$vundle_dir/README.md')
if filereadable(vundle_readme)
  set rtp+="$vundle_dir"
  call vundle#rc()

  \" Let Vundle manage Vundle
  Plugin 'gmarik/Vundle.vim'
  call SourceFiles('$dotfiles_dir', '*.vimp')

endif

filetype plugin indent on
" > "$HOME/.vimrc"
  habitat_debug "Installing $HOME/.vimrc and updating plugins"

  (vim +PluginClean +PluginInstall +qall 2>/dev/null 1>/dev/null &)
}

function habitat_brandonocasey_habitat_manage_vim_options() {
  local current_plugin_dir="$1"; shift
  local dotfiles_dir="$1"; shift
  echo 'brandonocasey/habitat-manage-vim does not support options'
}

