#!/usr/bin/env bash

function habitat_brandonocasey_habitat_manage_vim_run() {
  local current_plugin_dir="$1"; shift
  local dotfiles_dir="$1"; shift
  # install vundle in the background if not installed

  local bundle_dir="$HOME/.vim/bundle"
  local vundle_repo="VundleVim/Vundle.vim"
  local vundle_dir="$bundle_dir/$(basename "$vundle_repo")"
  local vundle_url="https://github.com/$vundle_repo"
  if [ ! -f "$vundle_dir/README.md" ]; then
    mkdir -p "$vundle_dir"
    (cd "$bundle_dir" && git clone "$vundle_url" 2>/dev/null 1>/dev/null &)
  fi

  echo "

function! SourceFiles(path, search)
  let path = expand(a:path)
  let files_found = system(\"find '\" . path . \"' -not -type l -name  '\" . a:search . \"'\")
  if empty(files_found)
    return
  endif
  for FILE in split(files_found, '\\n')
    exe 'source' FILE
  endfor
endfunction

function! AddPlugins(path, search)
  let path = expand(a:path)
  let files_found = system(\"find '\" . path . \"' -not -type l -name  '\" . a:search . \"'\")
  if empty(files_found)
    return
  endif
  for plugin in split(files_found, '\n')
    let plugin = fnamemodify(plugin, ':t')
    let plugin = substitute(plugin, '___', '/', '')
    let plugin = substitute(plugin, '.vimp', '', '')
    Plugin plugin
  endfor
endfunction


\" Source in all vimc files
call SourceFiles('$dotfiles_dir', '*.vimc')

\" Use Vundle and source .vimp files
let vundle_readme=expand('$vundle_dir/README.md')
if filereadable(vundle_readme)
  \" be iMproved, required
  set nocompatible

  \" required
  filetype off

  set rtp+="$vundle_dir"
  call vundle#begin()

  \" Let Vundle manage Vundle
  Plugin '$vundle_repo'
  call AddPlugins('$dotfiles_dir', '*.vimp')

  call vundle#end()

  call SourceFiles('$dotfiles_dir', '*.vimp')
  filetype plugin indent on

endif

" > "$HOME/.vimrc"
  habitat_debug "Installing $HOME/.vimrc and updating plugins"

  (vim +PluginClean +PluginInstall +qall 2>/dev/null 1>/dev/null &)
}

function habitat_brandonocasey_habitat_manage_vim_options() {
  local current_plugin_dir="$1"; shift
  local dotfiles_dir="$1"; shift
  echo 'brandonocasey/habitat-manage-vim does not support options'
}
